In [1]:
import torch
import torch.nn as nn

# permute()
## 主要作用：变换tensor维度
### 参数：一系列的整数，代表原来张量的维度。比如，对于三维的张量，维度分别对应0，1，2
#### 以下是实例，对于a = torch.randn(2, 3, 5)，尝试将其变换成torch.Size([3, 5, 2])的形状，因此，使用a.permute(1, 2, 0)

In [24]:
a = torch.randn(2, 3, 5)
a.size()

torch.Size([2, 3, 5])

In [25]:
a.permute(1, 2, 0).size() 

torch.Size([3, 5, 2])

#### 另一个实例，对于b=torch.randn(1,2,3,4)，尝试将其变换成torch.Size([4,3,2,1])的形状，使用b.permute(3,2,1,0)

In [29]:
b = torch.randn(1, 2, 3, 4)
b.size()

torch.Size([1, 2, 3, 4])

In [32]:
b.permute(3,2,1,0).size()

torch.Size([4, 3, 2, 1])

#### 值得注意的是，permute和transpose不一样，transpose仅仅能对二维的张量进行转置，不能操作高维的向量，以下是transpose的例子

In [31]:
c = torch.randn(1, 2)
c.size()

torch.Size([1, 2])

In [33]:
c.t().size()

torch.Size([2, 1])

# nn.AvgPool1d()
## 主要作用：对一维数据进行池化操作，常用于时序数据
### 主要参数：kernel_size---池化窗口的大小，stride---窗口移动的步长，默认等于kernel_size，padding---对输入的边界进行填充
#### 以下是实例，对于input=torch.tensor([[[1.,2,3,4,5,6,7]]])，将其经过一个kernel_size=3,stride=2的池化层

In [27]:
input=torch.tensor([[[1.,2,3,4,5,6,7]]])
pool1 = nn.AvgPool1d(kernel_size=3, stride=2)
pool1(input)

tensor([[[2., 4., 6.]]])

#### 另一个实例，将输入经过kernel_size=3, stride=1的池化层

In [34]:
pool2 = nn.AvgPool1d(kernel_size=3, stride=1)
pool2(input)

tensor([[[2., 3., 4., 5., 6.]]])

#### 对于padding，如果padding=0，证明没有在输入边界进行填充

In [35]:
pool3 = nn.AvgPool1d(kernel_size=3, stride=1,padding=0)
pool3(input)

tensor([[[2., 3., 4., 5., 6.]]])

#### 输出没有受到影响，尝试将padding改为1

In [36]:
pool4 = nn.AvgPool1d(kernel_size=3, stride=1,padding=1)
pool4(input)

tensor([[[1.0000, 2.0000, 3.0000, 4.0000, 5.0000, 6.0000, 4.3333]]])

#### 可以看到，padding的填充会为输出增加一个额外的池化窗口，进而导致增加了一个额外的输出
#### nn.AvgPool1d各个参数对于输出的影响可以参考pytorch文档：https://pytorch.org/docs/1.11/generated/torch.nn.AvgPool1d.html